"use client";

import React, { useState } from "react";
import { Wrench, Copy, Check, RefreshCw, Sparkles, Terminal, KeyRound } from "lucide-react";

export default function InteractiveTool() {
  const [activeTab, setActiveTab] = useState<"json2go" | "tokenGen">("json2go");
  const [copied, setCopied] = useState(false);

  // --- Tool 1: JSON to Go Struct ---
  const defaultJson = `{\n  "id": 1024,\n  "username": "ciooool",\n  "is_active": true,\n  "role": "indie_hacker",\n  "skills": ["Next.js", "Go", "TypeScript"],\n  "profile": {\n    "location": "Remote",\n    "followers": 880\n  }\n}`;

  const [jsonInput, setJsonInput] = useState(defaultJson);
  const [structName, setStructName] = useState("UserProfile");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // Convert JSON to Go Struct
  const generateGoStruct = (jsonStr: string, name: string): string => {
    try {
      const parsed = JSON.parse(jsonStr);
      if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
        return "// 请输入有效的 JSON Object（如 { ... }）";
      }

      const toCamelCase = (str: string) => {
        return str
          .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
          .replace(/^(.)/, (c) => c.toUpperCase());
      };

      const inferType = (val: unknown, key: string, nestedStructs: string[]): string => {
        if (val === null) return "interface{}";
        if (typeof val === "string") return "string";
        if (typeof val === "number") {
          return Number.isInteger(val) ? "int64" : "float64";
        }
        if (typeof val === "boolean") return "bool";
        if (Array.isArray(val)) {
          if (val.length === 0) return "[]interface{}";
          const elemType = inferType(val[0], key, nestedStructs);
          return `[]${elemType}`;
        }
        if (typeof val === "object") {
          const subName = toCamelCase(key) + "Info";
          const subCode = generateSingleStruct(val as Record<string, unknown>, subName, nestedStructs);
          nestedStructs.push(subCode);
          return subName;
        }
        return "interface{}";
      };

      const nestedStructs: string[] = [];

      const generateSingleStruct = (obj: Record<string, unknown>, sName: string, subList: string[]) => {
        const fields = Object.entries(obj).map(([key, val]) => {
          const fieldName = toCamelCase(key);
          const fieldType = inferType(val, key, subList);
          return `\t${fieldName.padEnd(16, " ")} ${fieldType.padEnd(12, " ")} \`json:"${key}"\``;
        });

        return `type ${sName} struct {\n${fields.join("\n")}\n}`;
      };

      const rootCode = generateSingleStruct(parsed as Record<string, unknown>, name || "AutoGenerated", nestedStructs);
      return [rootCode, ...nestedStructs].join("\n\n");
    } catch (e: unknown) {
      const err = e instanceof Error ? e.message : "JSON 解析失败";
      return `// 错误: ${err}\n// 请检查 JSON 格式是否有误`;
    }
  };

  const goStructOutput = generateGoStruct(jsonInput, structName);

  // --- Tool 2: Secure Secret / Token Generator ---
  const [tokenLength, setTokenLength] = useState(32);
  const [tokenPrefix, setTokenPrefix] = useState("dev_sec_");
  const [generatedToken, setGeneratedToken] = useState("dev_sec_9f7c2a1e8d4b6035cb58ae7012de9402");

  const generateNewToken = () => {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let res = "";
    const array = new Uint8Array(tokenLength);
    window.crypto.getRandomValues(array);
    for (let i = 0; i < tokenLength; i++) {
      res += chars[array[i] % chars.length];
    }
    setGeneratedToken(tokenPrefix + res);
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section id="interactive-tool" className="py-16 md:py-24 bg-zinc-50/60 dark:bg-zinc-950/40 border-b border-zinc-200/60 dark:border-zinc-800/60">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-10">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-blue-100 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300 mb-3">
            <Sparkles className="h-3.5 w-3.5" />
            <span>现场可玩的微工具 Showcase</span>
          </div>
          <h2 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-white sm:text-4xl">
            DevForge 开发者即时工坊
          </h2>
          <p className="mt-2 text-sm sm:text-base text-zinc-600 dark:text-zinc-400">
            纯前端纯本地隐私计算，无服务端记录。随时随地解决日常编码中的高频重复操作。
          </p>
        </div>

        {/* Tool Shell Container */}
        <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm overflow-hidden">
          {/* Top Bar Navigation */}
          <div className="flex flex-wrap items-center justify-between border-b border-zinc-200 dark:border-zinc-800 px-4 py-3 bg-zinc-50/80 dark:bg-zinc-900/80">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setActiveTab("json2go")}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                  activeTab === "json2go"
                    ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900 shadow-xs"
                    : "text-zinc-600 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
                }`}
              >
                <Terminal className="h-3.5 w-3.5" />
                <span>JSON 转 Go Struct</span>
              </button>

              <button
                onClick={() => setActiveTab("tokenGen")}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                  activeTab === "tokenGen"
                    ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900 shadow-xs"
                    : "text-zinc-600 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white"
                }`}
              >
                <KeyRound className="h-3.5 w-3.5" />
                <span>安全密钥 / API Token 生成器</span>
              </button>
            </div>

            <div className="hidden sm:flex items-center gap-1.5 text-xs text-zinc-400">
              <span className="h-2 w-2 rounded-full bg-emerald-500"></span>
              <span>Client-side Engine Ready</span>
            </div>
          </div>

          {/* Tab 1: JSON to Go Struct */}
          {activeTab === "json2go" && (
            <div className="p-4 sm:p-6">
              <div className="flex flex-col sm:flex-row items-center justify-between gap-3 mb-4">
                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <span className="text-xs font-medium text-zinc-500 dark:text-zinc-400">结构体名称:</span>
                  <input
                    type="text"
                    value={structName}
                    onChange={(e) => setStructName(e.target.value)}
                    placeholder="StructName"
                    className="px-2.5 py-1 text-xs font-mono rounded border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white focus:outline-hidden focus:ring-1 focus:ring-blue-500"
                  />
                </div>
                <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
                  <button
                    onClick={() => setJsonInput(defaultJson)}
                    className="text-xs text-zinc-500 hover:text-zinc-800 dark:text-zinc-400 dark:hover:text-zinc-200 underline"
                  >
                    重置为示例
                  </button>
                  <button
                    onClick={() => handleCopy(goStructOutput)}
                    className="inline-flex items-center gap-1 px-3 py-1 rounded bg-zinc-900 text-white text-xs font-medium hover:bg-zinc-800 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-200 transition-colors"
                  >
                    {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
                    <span>{copied ? "已复制" : "复制代码"}</span>
                  </button>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                {/* Left: JSON Input */}
                <div className="flex flex-col">
                  <div className="text-xs font-semibold text-zinc-500 dark:text-zinc-400 mb-1.5 flex items-center justify-between">
                    <span>原始 JSON 输入</span>
                    <span className="font-mono text-[11px] text-zinc-400">JSON Payload</span>
                  </div>
                  <textarea
                    value={jsonInput}
                    onChange={(e) => setJsonInput(e.target.value)}
                    rows={12}
                    placeholder="在此粘贴任意 JSON 对象..."
                    className="w-full font-mono text-xs p-3 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 focus:outline-hidden focus:ring-1 focus:ring-blue-500 resize-none"
                  />
                </div>

                {/* Right: Go Struct Output */}
                <div className="flex flex-col">
                  <div className="text-xs font-semibold text-zinc-500 dark:text-zinc-400 mb-1.5 flex items-center justify-between">
                    <span>生成 Go Struct 代码</span>
                    <span className="font-mono text-[11px] text-blue-500">Golang Definition</span>
                  </div>
                  <pre className="w-full font-mono text-xs p-3 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-900 text-zinc-100 dark:bg-zinc-950 overflow-auto h-[230px] sm:h-[240px]">
                    <code>{goStructOutput}</code>
                  </pre>
                </div>
              </div>
            </div>
          )}

          {/* Tab 2: Token / API Key Generator */}
          {activeTab === "tokenGen" && (
            <div className="p-6">
              <div className="max-w-xl mx-auto space-y-6">
                <div>
                  <h3 className="text-base font-semibold text-zinc-900 dark:text-white mb-1">
                    高熵加密安全密钥生成器
                  </h3>
                  <p className="text-xs text-zinc-500 dark:text-zinc-400">
                    使用浏览器安全级 Web Crypto API（CSPRN）在本地生成，适合作为 JWT Secret、API Key 或数据库强密码。
                  </p>
                </div>

                {/* Token Output Box */}
                <div className="flex items-center gap-2 p-3 rounded-xl bg-zinc-900 text-white font-mono text-xs sm:text-sm overflow-hidden border border-zinc-800">
                  <span className="truncate flex-1 select-all">{generatedToken}</span>
                  <button
                    onClick={() => handleCopy(generatedToken)}
                    className="p-1.5 rounded hover:bg-zinc-800 text-zinc-400 hover:text-white transition-colors shrink-0"
                    title="复制到剪贴板"
                  >
                    {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
                  </button>
                  <button
                    onClick={generateNewToken}
                    className="p-1.5 rounded hover:bg-zinc-800 text-zinc-400 hover:text-white transition-colors shrink-0"
                    title="重新生成"
                  >
                    <RefreshCw className="h-4 w-4" />
                  </button>
                </div>

                {/* Controls */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
                  <div>
                    <label className="text-xs font-medium text-zinc-700 dark:text-zinc-300 block mb-1">
                      前缀标识 (Prefix):
                    </label>
                    <input
                      type="text"
                      value={tokenPrefix}
                      onChange={(e) => setTokenPrefix(e.target.value)}
                      placeholder="e.g. dev_sec_, jwt_"
                      className="w-full px-3 py-1.5 text-xs font-mono rounded-lg border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-900 dark:text-white"
                    />
                  </div>

                  <div>
                    <label className="text-xs font-medium text-zinc-700 dark:text-zinc-300 block mb-1">
                      密钥长度 ({tokenLength} 位随机字符):
                    </label>
                    <input
                      type="range"
                      min={16}
                      max={64}
                      value={tokenLength}
                      onChange={(e) => setTokenLength(Number(e.target.value))}
                      className="w-full accent-blue-600 cursor-pointer"
                    />
                  </div>
                </div>

                <div className="text-center pt-2">
                  <button
                    onClick={generateNewToken}
                    className="inline-flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-blue-600 text-white text-xs font-semibold hover:bg-blue-700 transition-colors shadow-sm"
                  >
                    <RefreshCw className="h-3.5 w-3.5" />
                    <span>即刻生成新密钥</span>
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
