"use client";

import React, { useState } from "react";
import { Terminal, KeyRound, Copy, Check, RefreshCw } from "lucide-react";

export default function InteractiveTool() {
  const [activeTab, setActiveTab] = useState<"json2go" | "tokenGen">("json2go");

  // Tool 1: JSON to Go Struct
  const defaultJson = `{\n  "id": "usr_9981",\n  "username": "ciooool",\n  "roles": ["admin", "maker"],\n  "profile": {\n    "avatar": "https://ciooool.dev/icon.svg",\n    "followers": 1280,\n    "verified": true\n  }\n}`;
  const [jsonInput, setJsonInput] = useState<string>(defaultJson);
  const [structName, setStructName] = useState<string>("UserPayload");
  const [copied, setCopied] = useState<boolean>(false);

  // Tool 2: Token / API Key Generator
  const [tokenFormat, setTokenFormat] = useState<"base62" | "hex" | "uuid" | "base64">("base62");
  const [tokenPrefix, setTokenPrefix] = useState<string>("dev_sec_");
  const [tokenLength, setTokenLength] = useState<number>(32);
  const [generatedToken, setGeneratedToken] = useState<string>(
    "dev_sec_8F3aK9mQ2xL5vP1wZ7yT4nC6bE0hU"
  );

  // Convert JSON to Go Struct (支持递归嵌套解析与精准错误提示)
  const generateGoStruct = (jsonStr: string, name: string): string => {
    if (!jsonStr.trim()) {
      return "// 请在左侧输入或粘贴 JSON 对象...";
    }
    try {
      const obj = JSON.parse(jsonStr);
      if (typeof obj !== "object" || obj === null || Array.isArray(obj)) {
        return "// 提示: 顶层必须是一个 JSON Object (例如 {\"id\": 1, \"name\": \"demo\"})";
      }

      const toPascalCase = (str: string) => {
        return str
          .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
          .replace(/^(.)/, (_, c) => c.toUpperCase());
      };

      const getType = (val: any, indentLevel = 1): string => {
        if (val === null) return "any";
        if (typeof val === "boolean") return "bool";
        if (typeof val === "number") return Number.isInteger(val) ? "int64" : "float64";
        if (typeof val === "string") return "string";
        if (Array.isArray(val)) {
          if (val.length === 0) return "[]any";
          return `[]${getType(val[0], indentLevel)}`;
        }
        if (typeof val === "object") {
          const indent = "\t".repeat(indentLevel);
          const innerIndent = "\t".repeat(indentLevel + 1);
          let inner = "struct {\n";
          for (const [k, v] of Object.entries(val)) {
            inner += `${innerIndent}${toPascalCase(k)}\t${getType(v, indentLevel + 1)}\t\`json:"${k}"\`\n`;
          }
          inner += `${indent}}`;
          return inner;
        }
        return "any";
      };

      let result = `type ${name || "AutoGenerated"} struct {\n`;
      for (const [key, value] of Object.entries(obj)) {
        const fieldName = toPascalCase(key);
        const typeName = getType(value, 1);
        result += `\t${fieldName}\t${typeName}\t\`json:"${key}"\`\n`;
      }
      result += "}";
      return result;
    } catch (err: any) {
      return `// JSON 语法解析错误:\n// ${err?.message || "请输入有效格式"}`;
    }
  };

  const goStructOutput = generateGoStruct(jsonInput, structName);

  const formatJson = () => {
    try {
      const parsed = JSON.parse(jsonInput);
      setJsonInput(JSON.stringify(parsed, null, 2));
    } catch {
      // ignore
    }
  };

  const generateNewToken = () => {
    let result = "";
    if (tokenFormat === "uuid") {
      result = (typeof crypto.randomUUID === "function") 
        ? crypto.randomUUID()
        : "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
            const r = (Math.random() * 16) | 0;
            return (c === "x" ? r : (r & 0x3) | 0x8).toString(16);
          });
      setGeneratedToken(tokenPrefix ? `${tokenPrefix}${result}` : result);
      return;
    }

    if (tokenFormat === "hex") {
      const bytes = new Uint8Array(Math.ceil(tokenLength / 2));
      window.crypto.getRandomValues(bytes);
      result = Array.from(bytes)
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("")
        .slice(0, tokenLength);
    } else if (tokenFormat === "base64") {
      const bytes = new Uint8Array(tokenLength);
      window.crypto.getRandomValues(bytes);
      result = btoa(String.fromCharCode(...bytes))
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=+$/, "")
        .slice(0, tokenLength);
    } else {
      // base62
      const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
      const bytes = new Uint8Array(tokenLength);
      window.crypto.getRandomValues(bytes);
      for (let i = 0; i < tokenLength; i++) {
        result += chars[bytes[i] % chars.length];
      }
    }
    setGeneratedToken(tokenPrefix ? `${tokenPrefix}${result}` : result);
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section id="interactive-tool" className="py-20 md:py-28 border-b border-[#1F2A4D]/80 relative">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-12">
          <div>
            <div className="inline-flex items-center gap-2 text-xs font-mono tracking-widest text-[#5CF2C4] uppercase mb-3">
              <span className="w-1.5 h-1.5 rounded-full bg-[#5CF2C4] shadow-[0_0_8px_#5CF2C4]" />
              <span>DEV FORGE · 案头微工具</span>
            </div>
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-mono font-bold text-[#EAF0FF] tracking-tight">
              工坊即时交互工具
            </h2>
            <p className="mt-3 text-sm sm:text-base text-[#9FB0D0] max-w-2xl font-sans leading-relaxed">
              纯前端本地隐私计算，零服务端中转。解决日常系统架构中的高频结构体代码转换与密码学安全密钥生成。
            </p>
          </div>
          <div className="mt-4 md:mt-0 text-xs font-mono tracking-wider text-[#8B7BFF]">
            CLIENT-SIDE ENGINE · 零外部依赖
          </div>
        </div>

        {/* Tool Shell Container */}
        <div className="rounded-2xl border border-[#1F2A4D] bg-[#0A0E1A]/80 backdrop-blur-md shadow-lg overflow-hidden">
          {/* Top Bar Navigation */}
          <div className="flex flex-wrap items-center justify-between border-b border-[#1F2A4D] px-5 py-3.5 bg-[#05070F]/80 font-mono">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setActiveTab("json2go")}
                className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                  activeTab === "json2go"
                    ? "bg-[#5CF2C4] text-[#05070F] shadow-[0_0_15px_rgba(92,242,196,0.35)]"
                    : "text-[#9FB0D0] hover:text-[#EAF0FF] hover:bg-[#1F2A4D]/40"
                }`}
              >
                <Terminal className="h-3.5 w-3.5" />
                <span>JSON 转 Go Struct</span>
              </button>

              <button
                onClick={() => setActiveTab("tokenGen")}
                className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                  activeTab === "tokenGen"
                    ? "bg-[#5CF2C4] text-[#05070F] shadow-[0_0_15px_rgba(92,242,196,0.35)]"
                    : "text-[#9FB0D0] hover:text-[#EAF0FF] hover:bg-[#1F2A4D]/40"
                }`}
              >
                <KeyRound className="h-3.5 w-3.5" />
                <span>安全密钥 / Token 生成</span>
              </button>
            </div>

            <div className="hidden sm:flex items-center gap-2 text-xs font-mono text-[#5CF2C4]">
              <span className="w-1.5 h-1.5 rounded-full bg-[#5CF2C4] animate-pulse" />
              <span>本地安全沙箱已就绪</span>
            </div>
          </div>

          {/* Tab 1: JSON to Go Struct */}
          {activeTab === "json2go" && (
            <div className="p-5 sm:p-7">
              <div className="flex flex-col sm:flex-row items-center justify-between gap-3 mb-4 font-mono">
                <div className="flex items-center gap-2 w-full sm:w-auto">
                  <span className="text-xs text-[#9FB0D0]">结构体名称:</span>
                  <input
                    type="text"
                    value={structName}
                    onChange={(e) => setStructName(e.target.value)}
                    placeholder="StructName"
                    className="px-3 py-1.5 text-xs font-mono rounded-lg border border-[#1F2A4D] bg-[#05070F] text-[#EAF0FF] focus:outline-none focus:border-[#5CF2C4]"
                  />
                </div>
                <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
                  <button
                    onClick={formatJson}
                    className="text-xs text-[#9FB0D0] hover:text-[#5CF2C4] px-2.5 py-1 rounded-lg border border-[#1F2A4D] bg-[#05070F] hover:border-[#5CF2C4]/50 transition-colors"
                  >
                    格式化
                  </button>
                  <button
                    onClick={() => setJsonInput(defaultJson)}
                    className="text-xs text-[#7D88AA] hover:text-[#EAF0FF] px-2 py-1 transition-colors"
                  >
                    重置示例
                  </button>
                  <button
                    onClick={() => handleCopy(goStructOutput)}
                    className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-xl bg-[#5CF2C4] text-[#05070F] text-xs font-bold hover:bg-[#7DF9D2] hover:shadow-[0_0_15px_rgba(92,242,196,0.35)] transition-all"
                  >
                    {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
                    <span>{copied ? "已复制" : "复制代码"}</span>
                  </button>
                </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                {/* Left: JSON Input */}
                <div className="flex flex-col">
                  <div className="text-xs font-mono text-[#7D88AA] mb-1.5 flex items-center justify-between">
                    <span>原始 JSON 输入</span>
                    <span className="text-[10px]">JSON Payload</span>
                  </div>
                  <textarea
                    value={jsonInput}
                    onChange={(e) => setJsonInput(e.target.value)}
                    rows={12}
                    placeholder="在此粘贴任意 JSON 对象..."
                    className="w-full font-mono text-xs p-4 rounded-xl border border-[#1F2A4D] bg-[#05070F] text-[#EAF0FF] focus:outline-none focus:border-[#5CF2C4] resize-none leading-relaxed"
                  />
                </div>

                {/* Right: Go Struct Output */}
                <div className="flex flex-col">
                  <div className="text-xs font-mono text-[#7D88AA] mb-1.5 flex items-center justify-between">
                    <span>生成 Go Struct 代码</span>
                    <span className="text-[10px] text-[#5CF2C4]">Golang Definition</span>
                  </div>
                  <pre className="w-full font-mono text-xs p-4 rounded-xl border border-[#1F2A4D] bg-[#05070F] text-[#5CF2C4] overflow-auto h-[230px] sm:h-[240px] leading-relaxed">
                    <code>{goStructOutput}</code>
                  </pre>
                </div>
              </div>
            </div>
          )}

          {/* Tab 2: Token / API Key Generator */}
          {activeTab === "tokenGen" && (
            <div className="p-6 sm:p-8">
              <div className="max-w-xl mx-auto space-y-6">
                <div>
                  <h3 className="text-base font-sans font-bold text-[#EAF0FF] mb-1">
                    高熵加密安全密钥生成器
                  </h3>
                  <p className="text-xs font-mono text-[#9FB0D0]">
                    使用浏览器安全级 Web Crypto API 在本地加密生成，适合作为 JWT Secret、API Key 或生产强密码。
                  </p>
                </div>

                {/* 格式选择 */}
                <div>
                  <label className="text-xs text-[#9FB0D0] block mb-2 font-mono">
                    密钥格式 (Format):
                  </label>
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 font-mono text-xs">
                    {[
                      { id: "base62", label: "Base62" },
                      { id: "hex", label: "Hex 16进制" },
                      { id: "uuid", label: "UUID v4" },
                      { id: "base64", label: "Base64URL" },
                    ].map((fmt) => (
                      <button
                        key={fmt.id}
                        onClick={() => {
                          setTokenFormat(fmt.id as any);
                        }}
                        className={`px-3 py-1.5 rounded-lg border transition-all ${
                          tokenFormat === fmt.id
                            ? "bg-[#5CF2C4]/20 border-[#5CF2C4] text-[#5CF2C4] font-bold"
                            : "bg-[#05070F] border-[#1F2A4D] text-[#9FB0D0] hover:border-[#8B7BFF]"
                        }`}
                      >
                        {fmt.label}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Token Output Box */}
                <div className="flex items-center gap-2 p-3.5 rounded-xl bg-[#05070F] text-[#5CF2C4] font-mono text-xs sm:text-sm overflow-hidden border border-[#1F2A4D]">
                  <span className="truncate flex-1 select-all font-bold">{generatedToken}</span>
                  <button
                    onClick={() => handleCopy(generatedToken)}
                    className="p-1.5 rounded-lg hover:bg-[#1F2A4D]/60 text-[#9FB0D0] hover:text-[#EAF0FF] transition-colors shrink-0"
                    title="复制到剪贴板"
                  >
                    {copied ? <Check className="h-4 w-4 text-[#5CF2C4]" /> : <Copy className="h-4 w-4" />}
                  </button>
                  <button
                    onClick={generateNewToken}
                    className="p-1.5 rounded-lg hover:bg-[#1F2A4D]/60 text-[#9FB0D0] hover:text-[#5CF2C4] transition-colors shrink-0"
                    title="重新生成"
                  >
                    <RefreshCw className="h-4 w-4" />
                  </button>
                </div>

                {/* Controls */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2 font-mono">
                  <div>
                    <label className="text-xs text-[#9FB0D0] block mb-1">
                      前缀标识 (Prefix):
                    </label>
                    <input
                      type="text"
                      value={tokenPrefix}
                      onChange={(e) => setTokenPrefix(e.target.value)}
                      placeholder="e.g. dev_sec_, jwt_"
                      className="w-full px-3 py-2 text-xs font-mono rounded-lg border border-[#1F2A4D] bg-[#05070F] text-[#EAF0FF] focus:outline-none focus:border-[#5CF2C4]"
                    />
                  </div>

                  <div>
                    <label className="text-xs text-[#9FB0D0] block mb-1">
                      密钥长度 ({tokenLength} 位字符):
                    </label>
                    <input
                      type="range"
                      min={16}
                      max={64}
                      value={tokenLength}
                      disabled={tokenFormat === "uuid"}
                      onChange={(e) => setTokenLength(Number(e.target.value))}
                      className="w-full accent-[#5CF2C4] cursor-pointer mt-2 disabled:opacity-30"
                    />
                  </div>
                </div>

                <div className="text-center pt-2 font-mono">
                  <button
                    onClick={generateNewToken}
                    className="inline-flex items-center gap-2 px-6 py-2.5 rounded-xl bg-[#5CF2C4] text-[#05070F] text-xs font-bold hover:bg-[#7DF9D2] hover:shadow-[0_0_15px_rgba(92,242,196,0.35)] transition-all shadow-sm"
                  >
                    <RefreshCw className="h-3.5 w-3.5" />
                    <span>即刻生成新密钥</span>
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
